declare module "react-star-ratings";
declare module "bcryptjs";
declare module "react-js-pagination"
declare module "moment"
declare module "react-datepicker"
declare module "nodemailer"
declare module "paymongo"
declare module "pg"
declare module "chart.js"
declare module "jspdf"